name: Dump SONIC 2011 data.win

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SONIC 2011 Unenigmatic
        shell: pwsh
        run: |
          .\inject.exe

      - name: Check dump
        shell: pwsh
        run: |
          if (-not (Test-Path "./dump/datawin.dump")) {
              Write-Error "datawin.dump não foi criado."
              exit 1
          }

          Get-Item "./dump/datawin.dump"

      - name: Upload data.win dump
        uses: actions/upload-artifact@v4
        with:
          name: sonic-data-win
          path: dump/datawin.dump
